### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by CHRiceRice** [Steve-xmh/aerfaying-theme-manager#1]
![image](https://user-images.githubusercontent.com/53341861/100709659-78ae0880-33e9-11eb-9ada-9f64000ca34e.png)

![image](https://user-images.githubusercontent.com/53341861/100709629-6b911980-33e9-11eb-825e-5779ef661e12.png)

**Comment by Steve-xmh** [comment]
Icons are original, they are not transparent.
